services:
  api:
    build: .
    command: gunicorn -w 4 --bind 0.0.0.0:5001 run:app
    ports:
      - 5001:5001
  celery:
    build: .
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - api
  flower:
    build: .
    command: celery -A run.celery flower --address=0.0.0.0 --port=5555
    ports:
      - 5555:5555
    depends_on:
      - celery