services:
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build: .
    command: gunicorn -w 4 --bind 0.0.0.0:5001 run:app
    ports:
      - 5001:5001
  celery:
    build: .
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - api